[build]
  # This tells Netlify where your public front-end files are.
  publish = "public"
  # This tells Netlify where your serverless functions are.
  functions = "netlify/functions"

# This rule makes it so when your front-end calls "/.netlify/functions/ask-gemini",
# it correctly routes to your function.
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200